#
# This script updates all structural files of this repository, esp. the github action configuration of Dependabot.
#
$ErrorActionPreference = [Management.Automation.ActionPreference]::Stop

$yaml = @"
# Dependabot
# Generated by Update.ps1
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # github actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  # project nugets
"@

Get-ChildItem -Recurse -Include *.csproj $PSScriptRoot | ForEach-Object {
    $rp = [string](Resolve-Path -Relative -Path ($_.Directory))
    if ($rp -like ".\*") {
        $rp = $rp.Substring(2)
    }
    return $rp
} | ForEach-Object {
    $d = $_.Replace("`\", "/")
    $yaml += @"

  - package-ecosystem: "nuget"
    directory: "$d"
    schedule:
      interval: "weekly"
      day: "saturday"
    open-pull-requests-limit: 10
"@
}

Set-Content -Value $yaml -Path (Join-Path $PSScriptRoot ".github\dependabot.yml") -Encoding utf8NoBOM
